app = "ninja-gold"
primary_region = "ord"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["web"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[build]
  builder = "heroku/builder:22"

[deploy]
  release_command = "python manage.py migrate"

[processes]
  web = "gunicorn --bind 0.0.0.0:8000 myninja_gold.wsgi"
